import type {
  ArtifactBundle,
  DecompositionResult,
  DiscoveryResult,
  GeneratedArtifact,
  StackType,
  WorkloadRecommendation,
} from "./types.js";

function defaultPort(component: WorkloadRecommendation): number {
  return component.ports[0] ?? 8080;
}

function dockerBaseFor(stack: StackType): { image: string; packageCmd: string } {
  if (stack === "java-spring") {
    return {
      image: "eclipse-temurin:21-jre-alpine",
      packageCmd: "apk add --no-cache shadow",
    };
  }

  if (stack === "dotnet") {
    return {
      image: "mcr.microsoft.com/dotnet/aspnet:8.0-alpine",
      packageCmd: "apk add --no-cache shadow",
    };
  }

  if (stack === "nodejs") {
    return {
      image: "node:22-alpine",
      packageCmd: "apk add --no-cache shadow",
    };
  }

  if (stack === "python") {
    return {
      image: "python:3.12-alpine",
      packageCmd: "apk add --no-cache shadow",
    };
  }

  return {
    image: "cgr.dev/chainguard/wolfi-base:latest",
    packageCmd: "apk add --no-cache shadow",
  };
}

function runtimeCommandFor(stack: StackType, component: WorkloadRecommendation): string {
  if (stack === "java-spring") {
    return "CMD [\"sh\", \"-c\", \"java -jar /app/app.jar\"]";
  }

  if (stack === "dotnet") {
    return `CMD ["sh", "-c", "dotnet /app/${component.componentName}.dll"]`;
  }

  if (stack === "nodejs") {
    return "CMD [\"sh\", \"-c\", \"node /app/index.js\"]";
  }

  if (stack === "python") {
    return "CMD [\"sh\", \"-c\", \"python /app/main.py\"]";
  }

  return `CMD ["/bin/sh", "-c", "echo 'override runtime command for ${component.componentName}' && sleep infinity"]`;
}

function dockerfileFor(component: WorkloadRecommendation): string {
  const { image, packageCmd } = dockerBaseFor(component.stack);

  return `# Generated by Stratosphere
FROM ${image}

RUN ${packageCmd} \\
  && groupadd -g 10001 app \\
  && useradd -u 10001 -g app -M -s /sbin/nologin app

WORKDIR /app
COPY . /app

USER app
EXPOSE ${defaultPort(component)}
HEALTHCHECK --interval=30s --timeout=3s --start-period=20s CMD ["sh", "-c", "echo ok"]

# Stack detected: ${component.stack}
${runtimeCommandFor(component.stack, component)}
`;
}

function chartYaml(migrationId: string): string {
  return `apiVersion: v2
name: ${migrationId}-migration
version: 0.1.0
appVersion: "1.0"
description: Generated by Stratosphere migration architect
`;
}

function valuesYaml(recommendations: WorkloadRecommendation[]): string {
  const lines: string[] = [];
  lines.push("global:");
  lines.push("  imagePullPolicy: IfNotPresent");
  lines.push("  podSecurityContext:");
  lines.push("    runAsNonRoot: true");
  lines.push("    runAsUser: 10001");
  lines.push("    runAsGroup: 10001");
  lines.push("    fsGroup: 10001");
  lines.push("  containerSecurityContext:");
  lines.push("    allowPrivilegeEscalation: false");
  lines.push("    readOnlyRootFilesystem: false");
  lines.push("    capabilities:");
  lines.push("      drop: [\"ALL\"]");
  lines.push("");
  lines.push("components:");

  for (const item of recommendations) {
    lines.push(`  - id: ${item.componentId}`);
    lines.push(`    name: ${item.componentName}`);
    lines.push(`    stack: ${item.stack}`);
    lines.push(`    kind: ${item.kind}`);
    lines.push(`    replicas: ${item.kind === "StatefulSet" ? 1 : item.kind === "CronJob" ? 1 : 2}`);
    lines.push(`    image: ${item.imageTag}`);
    lines.push(`    schedule: ${item.schedule ? `"${item.schedule}"` : "\"\""}`);
    lines.push(`    ports: [${item.ports.join(", ")}]`);
    lines.push("    resources:");
    lines.push("      requests:");
    lines.push(`        cpu: ${item.resourceRecommendation.cpuRequestMillicores}m`);
    lines.push(`        memory: ${item.resourceRecommendation.memoryRequestMb}Mi`);
    lines.push("      limits:");
    lines.push(`        cpu: ${item.resourceRecommendation.cpuLimitMillicores}m`);
    lines.push(`        memory: ${item.resourceRecommendation.memoryLimitMb}Mi`);
    lines.push("    probes:");
    lines.push("      readinessPath: /health/ready");
    lines.push("      livenessPath: /health/live");
    lines.push("      startupPath: /health/startup");
    lines.push("    envConfig: []");
    lines.push("    envSecret: []");
    lines.push("    persistence:");
    lines.push(`      enabled: ${item.kind === "StatefulSet"}`);
    lines.push("      size: 20Gi");
    lines.push("");
  }

  return `${lines.join("\n")}\n`;
}

function serviceAccountTemplate(): string {
  return `apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-sa
`;
}

function configTemplates(): string {
  return `{{- range .Values.components }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .id }}-config
  labels:
    app: {{ .id }}
data:
  APP_NAME: {{ .name | quote }}
  APP_STACK: {{ .stack | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .id }}-secret
  labels:
    app: {{ .id }}
type: Opaque
stringData: {}
---
{{- end }}
`;
}

function workloadsTemplate(): string {
  return `{{- range .Values.components }}
{{- if eq .kind "Deployment" }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .id }}
  labels:
    app: {{ .id }}
spec:
  replicas: {{ .replicas }}
  selector:
    matchLabels:
      app: {{ .id }}
  template:
    metadata:
      labels:
        app: {{ .id }}
    spec:
      serviceAccountName: {{ $.Release.Name }}-sa
      securityContext: {{- toYaml $.Values.global.podSecurityContext | nindent 8 }}
      containers:
      - name: {{ .id }}
        image: {{ .image }}
        imagePullPolicy: {{ $.Values.global.imagePullPolicy }}
        securityContext: {{- toYaml $.Values.global.containerSecurityContext | nindent 10 }}
        resources: {{- toYaml .resources | nindent 10 }}
        envFrom:
        - configMapRef:
            name: {{ .id }}-config
        - secretRef:
            name: {{ .id }}-secret
        ports:
        {{- range .ports }}
        - containerPort: {{ . }}
        {{- end }}
        readinessProbe:
          httpGet:
            path: {{ .probes.readinessPath }}
            port: {{ default 8080 (index .ports 0) }}
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: {{ .probes.livenessPath }}
            port: {{ default 8080 (index .ports 0) }}
          initialDelaySeconds: 20
          periodSeconds: 20
        startupProbe:
          httpGet:
            path: {{ .probes.startupPath }}
            port: {{ default 8080 (index .ports 0) }}
          failureThreshold: 30
          periodSeconds: 10
---
{{- end }}
{{- if eq .kind "StatefulSet" }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .id }}
  labels:
    app: {{ .id }}
spec:
  serviceName: {{ .id }}
  replicas: {{ .replicas }}
  selector:
    matchLabels:
      app: {{ .id }}
  template:
    metadata:
      labels:
        app: {{ .id }}
    spec:
      serviceAccountName: {{ $.Release.Name }}-sa
      securityContext: {{- toYaml $.Values.global.podSecurityContext | nindent 8 }}
      containers:
      - name: {{ .id }}
        image: {{ .image }}
        imagePullPolicy: {{ $.Values.global.imagePullPolicy }}
        securityContext: {{- toYaml $.Values.global.containerSecurityContext | nindent 10 }}
        resources: {{- toYaml .resources | nindent 10 }}
        envFrom:
        - configMapRef:
            name: {{ .id }}-config
        - secretRef:
            name: {{ .id }}-secret
        ports:
        {{- range .ports }}
        - containerPort: {{ . }}
        {{- end }}
        readinessProbe:
          httpGet:
            path: {{ .probes.readinessPath }}
            port: {{ default 8080 (index .ports 0) }}
          initialDelaySeconds: 10
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: {{ .probes.livenessPath }}
            port: {{ default 8080 (index .ports 0) }}
          initialDelaySeconds: 20
          periodSeconds: 20
        volumeMounts:
        - name: data
          mountPath: /data
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: {{ .persistence.size }}
---
{{- end }}
{{- if eq .kind "CronJob" }}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ .id }}
spec:
  schedule: {{ .schedule | quote }}
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: {{ $.Release.Name }}-sa
          restartPolicy: OnFailure
          securityContext: {{- toYaml $.Values.global.podSecurityContext | nindent 10 }}
          containers:
          - name: {{ .id }}
            image: {{ .image }}
            imagePullPolicy: {{ $.Values.global.imagePullPolicy }}
            securityContext: {{- toYaml $.Values.global.containerSecurityContext | nindent 12 }}
            resources: {{- toYaml .resources | nindent 12 }}
            envFrom:
            - configMapRef:
                name: {{ .id }}-config
            - secretRef:
                name: {{ .id }}-secret
---
{{- end }}
{{- end }}
`;
}

function servicesTemplate(): string {
  return `{{- range .Values.components }}
{{- if gt (len .ports) 0 }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .id }}
  labels:
    app: {{ .id }}
spec:
  selector:
    app: {{ .id }}
  ports:
  - name: http
    port: {{ index .ports 0 }}
    targetPort: {{ index .ports 0 }}
---
{{- end }}
{{- end }}
`;
}

function networkPolicyTemplate(): string {
  return `apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Release.Name }}-default-deny-egress
spec:
  podSelector: {}
  policyTypes:
  - Egress
  egress:
  - to:
    - namespaceSelector: {}
  - to:
    - ipBlock:
        cidr: 0.0.0.0/0
    ports:
    - protocol: UDP
      port: 53
`;
}

function terraformMain(provider: "aws" | "azure" | "gcp" | "openstack"): string {
  if (provider === "aws") {
    return `terraform {
  required_version = ">= 1.6.0"
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 5.0"
    }
  }
}

provider "aws" {
  region = var.region
}

module "migration_namespace" {
  source         = "./modules/namespace"
  namespace_name = var.namespace
}
`;
  }

  if (provider === "azure") {
    return `terraform {
  required_version = ">= 1.6.0"
  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = "~> 4.0"
    }
  }
}

provider "azurerm" {
  features {}
}

module "migration_namespace" {
  source         = "./modules/namespace"
  namespace_name = var.namespace
}
`;
  }

  if (provider === "gcp") {
    return `terraform {
  required_version = ">= 1.6.0"
  required_providers {
    google = {
      source  = "hashicorp/google"
      version = "~> 6.0"
    }
  }
}

provider "google" {
  project = var.project_id
  region  = var.region
}

module "migration_namespace" {
  source         = "./modules/namespace"
  namespace_name = var.namespace
}
`;
  }

  return `terraform {
  required_version = ">= 1.6.0"
  required_providers {
    openstack = {
      source  = "terraform-provider-openstack/openstack"
      version = "~> 2.1"
    }
  }
}

provider "openstack" {
  auth_url    = var.auth_url
  tenant_name = var.tenant_name
  user_name   = var.user_name
  password    = var.password
  region      = var.region
}

module "migration_namespace" {
  source         = "./modules/namespace"
  namespace_name = var.namespace
}
`;
}

function terraformVariables(provider: "aws" | "azure" | "gcp" | "openstack"): string {
  const lines = [
    'variable "namespace" {',
    '  type    = string',
    '  default = "stratosphere-migration"',
    "}",
    "",
    'variable "region" {',
    '  type    = string',
    '  default = "us-east-1"',
    "}",
  ];

  if (provider === "gcp") {
    lines.push("", 'variable "project_id" {', "  type = string", "}");
  }

  if (provider === "openstack") {
    lines.push(
      "",
      'variable "auth_url" {',
      "  type = string",
      "}",
      'variable "tenant_name" {',
      "  type = string",
      "}",
      'variable "user_name" {',
      "  type = string",
      "}",
      'variable "password" {',
      "  type = string",
      "  sensitive = true",
      "}"
    );
  }

  return `${lines.join("\n")}\n`;
}

function terraformOutputs(): string {
  return `output "namespace" {
  value = var.namespace
}
`;
}

function terraformReadme(provider: "aws" | "azure" | "gcp" | "openstack"): string {
  return `# ${provider.toUpperCase()} Terraform Scaffold

This module set is generated by Stratosphere for migration bootstrapping.

## Notes
- Replace namespace module source with your organization module registry.
- Add IAM, storage, networking, and observability modules before production deployment.
- Keep this generated scaffold under version control.
`;
}

function decompositionReport(result: DecompositionResult): string {
  const lines: string[] = [];
  lines.push("# Decomposition Report");
  lines.push("");

  for (const recommendation of result.recommendations) {
    lines.push(`## ${recommendation.componentName}`);
    lines.push(`- Kind: ${recommendation.kind}`);
    lines.push(`- Stack: ${recommendation.stack}`);
    lines.push(`- Confidence: ${recommendation.confidence}`);
    lines.push(`- Ports: ${recommendation.ports.length > 0 ? recommendation.ports.join(", ") : "none"}`);
    lines.push(`- Dependencies: ${recommendation.dependencies.length > 0 ? recommendation.dependencies.join(", ") : "none"}`);
    lines.push("- Rationale:");
    for (const rationale of recommendation.rationale) {
      lines.push(`  - ${rationale}`);
    }
    lines.push("");
  }

  if (result.blockers.length > 0) {
    lines.push("## Blockers");
    for (const blocker of result.blockers) {
      lines.push(`- ${blocker}`);
    }
    lines.push("");
  }

  return `${lines.join("\n")}\n`;
}

function securityReport(recommendations: WorkloadRecommendation[]): string {
  const lines: string[] = [
    "# Security Baseline Notes",
    "",
    "Generated defaults include:",
    "- Non-root container execution",
    "- Dropped Linux capabilities",
    "- Liveness/readiness/startup probes",
    "- ConfigMap/Secret split templates",
    "- Default egress policy template",
    "",
    "## Component-specific Notes",
  ];

  for (const recommendation of recommendations) {
    lines.push(`- ${recommendation.componentName}: stack=${recommendation.stack}, kind=${recommendation.kind}`);
  }

  lines.push("");
  lines.push("Review all generated probes and environment injection before production rollout.");

  return `${lines.join("\n")}\n`;
}

function vmDnaReport(discovery: DiscoveryResult): string {
  return JSON.stringify(discovery, null, 2);
}

function addArtifact(artifacts: GeneratedArtifact[], path: string, content: string): void {
  artifacts.push({ path, content });
}

export function generateArtifacts(
  migrationId: string,
  discovery: DiscoveryResult,
  decomposition: DecompositionResult
): ArtifactBundle {
  const artifacts: GeneratedArtifact[] = [];

  for (const component of decomposition.recommendations) {
    addArtifact(artifacts, `docker/${component.componentId}/Dockerfile`, dockerfileFor(component));
  }

  addArtifact(artifacts, "helm/Chart.yaml", chartYaml(migrationId));
  addArtifact(artifacts, "helm/values.yaml", valuesYaml(decomposition.recommendations));
  addArtifact(artifacts, "helm/templates/serviceaccount.yaml", serviceAccountTemplate());
  addArtifact(artifacts, "helm/templates/config.yaml", configTemplates());
  addArtifact(artifacts, "helm/templates/workloads.yaml", workloadsTemplate());
  addArtifact(artifacts, "helm/templates/services.yaml", servicesTemplate());
  addArtifact(artifacts, "helm/templates/networkpolicy.yaml", networkPolicyTemplate());

  for (const provider of ["aws", "azure", "gcp", "openstack"] as const) {
    addArtifact(artifacts, `terraform/${provider}/main.tf`, terraformMain(provider));
    addArtifact(artifacts, `terraform/${provider}/variables.tf`, terraformVariables(provider));
    addArtifact(artifacts, `terraform/${provider}/outputs.tf`, terraformOutputs());
    addArtifact(artifacts, `terraform/${provider}/README.md`, terraformReadme(provider));
  }

  addArtifact(artifacts, "reports/decomposition.md", decompositionReport(decomposition));
  addArtifact(artifacts, "reports/security-baseline.md", securityReport(decomposition.recommendations));
  addArtifact(artifacts, "reports/vm-dna.json", vmDnaReport(discovery));

  return { artifacts };
}
