import type {
  ArtifactBundle,
  DecompositionResult,
  DiscoveryResult,
  GeneratedArtifact,
  WorkloadRecommendation,
} from "./types.js";

function dockerfileFor(component: WorkloadRecommendation): string {
  return `# Generated by Stratosphere
FROM cgr.dev/chainguard/wolfi-base:latest

RUN addgroup -S app && adduser -S app -G app
WORKDIR /app

# Replace with your actual build artifact copy logic.
COPY . /app

USER app
EXPOSE ${component.ports[0] ?? 8080}

# Replace with runtime command for ${component.componentName}
CMD ["/bin/sh", "-c", "echo 'override me for ${component.componentName}' && sleep infinity"]
`;
}

function chartYaml(migrationId: string): string {
  return `apiVersion: v2
name: ${migrationId}-migration
version: 0.1.0
appVersion: "1.0"
description: Generated by Stratosphere migration architect
`;
}

function valuesYaml(recommendations: WorkloadRecommendation[]): string {
  const lines: string[] = [];
  lines.push("global:");
  lines.push("  imagePullPolicy: IfNotPresent");
  lines.push("");
  lines.push("components:");

  for (const item of recommendations) {
    lines.push(`  - id: ${item.componentId}`);
    lines.push(`    name: ${item.componentName}`);
    lines.push(`    kind: ${item.kind}`);
    lines.push(`    image: ${item.imageTag}`);
    lines.push(`    schedule: ${item.schedule ?? "\"\""}`);
    lines.push(`    ports: [${item.ports.join(", ")}]`);
    lines.push("    resources:");
    lines.push("      requests:");
    lines.push(`        cpu: ${item.resourceRecommendation.cpuRequestMillicores}m`);
    lines.push(`        memory: ${item.resourceRecommendation.memoryRequestMb}Mi`);
    lines.push("      limits:");
    lines.push(`        cpu: ${item.resourceRecommendation.cpuLimitMillicores}m`);
    lines.push(`        memory: ${item.resourceRecommendation.memoryLimitMb}Mi`);
    lines.push("    env: []");
    lines.push("    persistence:");
    lines.push(`      enabled: ${item.kind === "StatefulSet"}`);
    lines.push("      size: 20Gi");
    lines.push("");
  }

  return `${lines.join("\n")}\n`;
}

function workloadsTemplate(): string {
  return `{{- range .Values.components }}
{{- if eq .kind "Deployment" }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .id }}
spec:
  replicas: 2
  selector:
    matchLabels:
      app: {{ .id }}
  template:
    metadata:
      labels:
        app: {{ .id }}
    spec:
      containers:
      - name: {{ .id }}
        image: {{ .image }}
        imagePullPolicy: {{ $.Values.global.imagePullPolicy }}
        resources: {{- toYaml .resources | nindent 10 }}
        ports:
        {{- range .ports }}
        - containerPort: {{ . }}
        {{- end }}
---
{{- end }}
{{- if eq .kind "StatefulSet" }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .id }}
spec:
  serviceName: {{ .id }}
  replicas: 1
  selector:
    matchLabels:
      app: {{ .id }}
  template:
    metadata:
      labels:
        app: {{ .id }}
    spec:
      containers:
      - name: {{ .id }}
        image: {{ .image }}
        imagePullPolicy: {{ $.Values.global.imagePullPolicy }}
        resources: {{- toYaml .resources | nindent 10 }}
        ports:
        {{- range .ports }}
        - containerPort: {{ . }}
        {{- end }}
        volumeMounts:
        - name: data
          mountPath: /data
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: {{ .persistence.size }}
---
{{- end }}
{{- if eq .kind "CronJob" }}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ .id }}
spec:
  schedule: {{ .schedule | quote }}
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
          - name: {{ .id }}
            image: {{ .image }}
            imagePullPolicy: {{ $.Values.global.imagePullPolicy }}
            resources: {{- toYaml .resources | nindent 14 }}
---
{{- end }}
{{- end }}
`;
}

function servicesTemplate(): string {
  return `{{- range .Values.components }}
{{- if .ports }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .id }}
spec:
  selector:
    app: {{ .id }}
  ports:
  - name: http
    port: {{ index .ports 0 }}
    targetPort: {{ index .ports 0 }}
---
{{- end }}
{{- end }}
`;
}

function terraformMain(provider: "aws" | "azure" | "gcp" | "openstack"): string {
  if (provider === "aws") {
    return `terraform {
  required_version = ">= 1.6.0"
}

module "k8s_namespace" {
  source = "./modules/namespace"
  name   = "stratosphere-migration"
}

# Add EKS/IAM/storage resources for your target environment.
`;
  }

  if (provider === "azure") {
    return `terraform {
  required_version = ">= 1.6.0"
}

module "k8s_namespace" {
  source = "./modules/namespace"
  name   = "stratosphere-migration"
}

# Add AKS/Azure RBAC/networking resources for your target environment.
`;
  }

  if (provider === "gcp") {
    return `terraform {
  required_version = ">= 1.6.0"
}

module "k8s_namespace" {
  source = "./modules/namespace"
  name   = "stratosphere-migration"
}

# Add GKE/IAM/networking resources for your target environment.
`;
  }

  return `terraform {
  required_version = ">= 1.6.0"
}

module "k8s_namespace" {
  source = "./modules/namespace"
  name   = "stratosphere-migration"
}

# Add OpenStack provider, network, and Cinder-backed storage resources.
`;
}

function decompositionReport(result: DecompositionResult): string {
  const lines: string[] = [];
  lines.push("# Decomposition Report");
  lines.push("");

  for (const rec of result.recommendations) {
    lines.push(`## ${rec.componentName}`);
    lines.push(`- Kind: ${rec.kind}`);
    lines.push(`- Confidence: ${rec.confidence}`);
    lines.push(`- Ports: ${rec.ports.length > 0 ? rec.ports.join(", ") : "none"}`);
    lines.push(`- Dependencies: ${rec.dependencies.length > 0 ? rec.dependencies.join(", ") : "none"}`);
    lines.push("- Rationale:");
    for (const rationale of rec.rationale) {
      lines.push(`  - ${rationale}`);
    }
    lines.push("");
  }

  if (result.blockers.length > 0) {
    lines.push("## Blockers");
    for (const blocker of result.blockers) {
      lines.push(`- ${blocker}`);
    }
    lines.push("");
  }

  return `${lines.join("\n")}\n`;
}

function vmDnaReport(discovery: DiscoveryResult): string {
  return JSON.stringify(discovery, null, 2);
}

function addArtifact(artifacts: GeneratedArtifact[], path: string, content: string): void {
  artifacts.push({ path, content });
}

export function generateArtifacts(
  migrationId: string,
  discovery: DiscoveryResult,
  decomposition: DecompositionResult
): ArtifactBundle {
  const artifacts: GeneratedArtifact[] = [];

  for (const component of decomposition.recommendations) {
    addArtifact(artifacts, `docker/${component.componentId}/Dockerfile`, dockerfileFor(component));
  }

  addArtifact(artifacts, "helm/Chart.yaml", chartYaml(migrationId));
  addArtifact(artifacts, "helm/values.yaml", valuesYaml(decomposition.recommendations));
  addArtifact(artifacts, "helm/templates/workloads.yaml", workloadsTemplate());
  addArtifact(artifacts, "helm/templates/services.yaml", servicesTemplate());

  for (const provider of ["aws", "azure", "gcp", "openstack"] as const) {
    addArtifact(artifacts, `terraform/${provider}/main.tf`, terraformMain(provider));
  }

  addArtifact(artifacts, "reports/decomposition.md", decompositionReport(decomposition));
  addArtifact(artifacts, "reports/vm-dna.json", vmDnaReport(discovery));

  return { artifacts };
}
